apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: elasticsearch-master
  labels:
    app: elasticsearch
    role: master
spec:
  type: NodePort
  selector:
    app: elasticsearch
    role: master
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30920
      name: http
    - port: 9300
      name: node-to-node
