kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: log-pipeline
spec:
  template:
    metadata:
      labels:
        app: log-pipeline
    spec:
      hostname: log-pipeline
      containers:
      - name: log-pipeline
        ports:
          - containerPort: 5000
            name: logtcp
          - containerPort: 9600
            name: logstash
        image: docker.elastic.co/logstash/logstash:6.5.0
        volumeMounts:
        - name: log-pipeline-config
          mountPath: /usr/share/logstash/pipeline/
        command:
        - logstash
      volumes:
      - name: log-pipeline-config
        configMap:
          name: log-pipeline
          items:
          - key: logstash-es.conf
            path: logstash-es.conf
---
kind: Service
apiVersion: v1
metadata:
  name: log-pipeline
spec:
  type: NodePort
  selector:
    app: log-pipeline
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30500
    name: logtcp
  - protocol: TCP
    port: 9600
    targetPort: 9600
    name: logstash
