apiVersion: v1
kind: Service
metadata:
  name: aftersales-gw-service
spec:
  type: NodePort
  ports:
    - port: 9001
      targetPort: 9001
      nodePort: 30091
  selector:
    app: sit-bmw-aftersales-gw
