apiVersion: v1
kind: PersistentVolume
metadata:
  name: sales-dataset-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/data/sales-db
