apiVersion: v1
kind: Service
metadata:
  name: sales-postgresql
  labels:
    app: sales-postgresql
spec:
  type: NodePort
  ports:
   - port: 5432
     targetPort: 5432
     nodePort: 31543
  selector:
   app: sales-postgresql
