apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sales-postgresql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sales-postgresql
    spec:
      containers:
        - name: sales-postgresql
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: sales-postgresql-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: ai-sales-pv-claim
