apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: progress-prometheus-server
  namespace: sit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: progress-prometheus-server
    spec:
      containers:
        - name: progress-prometheus-server
          image: prom/prometheus:v2.2.1
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-progress-conf
        - name: prometheus-storage-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: progress-prometheus-server
  namespace: sit
spec:
  selector: 
    app: progress-prometheus-server
  ports:
    - port: 9090
      targetPort: 9090
