apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-sales-gw-conf
  labels:
    name: prometheus-sales-gw-conf
  namespace: sit
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'spring-actuator'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
        - targets: ['sales-gw-service:9000']
