apiVersion: v1
kind: Service
metadata:
  name: sonar-postgresql
  labels:
    app: sonar-postgresql
spec:
  type: NodePort
  ports:
   - port: 5432
     targetPort: 5432
     nodePort: 32001
  selector:
   app: sonar-postgresql
