apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-extension-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/data/sonar-extension
